name: Tests

on:
  push:
    branches:
    - master
    - feature/*
    - hotfix/*
    - patch/*

jobs:
  netcore:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Variable substitution
      uses: microsoft/variable-substitution@v1 
      with:
        files: 'Fortnox.NET.Tests\Fortnox.NET.Tests\appsettings.json'
      env:
        AccessToken: ${{ secrets.ACCESSTOKEN }}
        ClientSecret: ${{ secrets.CLIENTSECRET }}

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          5.0.x
          6.0.x

    
    - name: Install dependencies
      shell: cmd
      run: |
        cd Fortnox.NET
        dotnet restore
    
    - name: Build
      shell: cmd
      run: |
        cd Fortnox.NET
        dotnet build --configuration Release --no-restore
